import Image from "next/image";
import React from "react";
import bft from "../../../assets/images/pvt-reg/benefit.svg";

const CFOServices = () => {
  return (
    <div id="CFOServices">
      <p className="main-para">
        The following are the reasons behind getting Virtual CFO Services:
      </p>
      <div className="benefits flex w-80 m-auto mobile-flex-column">
      <div className="flex-3">
          <Image
            alt=""
            className="CFOServices-img w-100"
            height={480}
            loading="lazy"
            src={bft}
          />
        </div>
        <div className="flex-7">
          <p>
            <strong>Accurate Accounting & Budgeting : </strong>
            Accuracy in Accounting and budgeting helps in strategizing
            companies’ policies, and plans for future expansion and this process
            becomes even more effective with a specialized CFO. RegisterKaro
            Virtual CFO makes sure that you receive best of CFO services
            optimizing your business at minimum investment.
          </p>

          <p>
            <strong>Improvised Profitability : </strong>
            Virtual CFO services helps you in optimizing the operations cost by
            cutting down on unnecessary expenditures with the help of efficient
            budgeting and accounting. This assist in generating higher revenue
            at comparatively lower rate of investment.
          </p>

          <p>
            <strong>Decision Making : </strong>
            Additionally, a virtual CFO supports the company’s decision-making
            process, which eventually promotes business expansion. It uses the
            identification of important operational indicators to analyze the
            company’s finances and operations and further optimizes those
            indicators to their best potential.
          </p>

          <p>
            <strong>Risk-Assessment : </strong>
            All businesses have risks which are sometimes hidden and sometimes
            easy to locate. These forms of risks are threats to any business
            causing the unforeseeable damages which can be time consuming to be
            retained back. Therefore, virtual CFO recognizes potential risks to
            provide solutions so that such risk can be curbed at all sort of
            level where there is any option to influence businesses.
          </p>

          <p>
            <strong>Success Oriented : </strong>
            Job of a CFO is to keep a check on the current market status and
            financial volatility to prepare the business for future bumps and
            dumps. This helps the business to bear certain level of market
            shrink. The virtual CFO evaluates factors like production, sales,
            distribution, cash flow, etc. to monitor the success-oriented
            trajectory.
          </p>

          <p>
            <strong>Growth Strategy : </strong>
            The virtual CFO guides in creating effective improvement plan,
            current business status report, future target evaluation, and the
            execution plan to achieve the goal for the targeted timeline. This
            helps in monitoring growth strategy to further modify the same as
            per the business requirement.
          </p>

          <p>
            <strong>Investor Access : </strong>
            On the basis of reports generated by Virtual CFO for the accounting
            and budgeting department, it is easier to gain access to investors
            for better business projection, depicting the business future
            growth.
          </p>

          <p>
            <strong>Mentoring valuations : </strong>
            It is really important to conduct business valuations timely to
            predict future prospects and modify current business practices for
            better optimization of all including assets, liabilities,
            securities, debt instruments, issued derivatives. Virtual CFO helps
            in conducting and improvising the valuation process smoothly.
          </p>

          <p>
            <strong>Organizational Hierarchy : </strong>
            Business operation is nothing but organized set of steps which
            results in a uniform conduction of practices. Therefore, it is
            really important that the structure of an organization is well
            equipped with the current market practices and matches the vision of
            business growth.
          </p>
        </div>
      
      </div>
    </div>
  );
};

export default CFOServices;
