import Head from 'next/head'
import { FaqTemplatePVT } from '../components/child_components/FaqTemplatePVT'
import { WhyRegisterkaro } from '../components/static/WhyRegisterkaro'
import { DocumentRequired } from '../components/static/csr-registration/DocumentRequired'
import FactsCsr from '../components/static/csr-registration/FactsCsr'
import { Hero } from '../components/static/csr-registration/Hero'
import { Process } from '../components/static/csr-registration/Process'
import { WhyChoose } from '../components/static/csr-registration/WhyChoose'
import ProcedureCsr from '../components/static/csr-registration/ProcedureCsr'

const faq = [
    {
        "question": "What’s the Purpose of CSR-1?",
        "answer": "As per the Companies (Corporate Social Responsibility Policy) Amendment Rules, 2021, a company has the option to carry out CSR initiatives either directly or through entities specified in Rule 4 sub rule (1). These companies/entities must register with the central government by submitting the e-form CSR-1 with the Registrar in order to engage in any CSR activities."
    },
    {
        "question": "How to apply for CSR funds in India?",
        "answer": "In order to request CSR funding in India, NGOs must adhere to these steps. Initially, collect all necessary paperwork for CSR-1 enrollment. Next, make sure to accurately complete the CSR-1 E-form from the MCA website and remember to attach any required certificates. Get certified by a Chartered Accountant, Company Secretary, or Cost & Management Accountant. Send the form through the MCA portal online and get a receipt containing a traceable SRN. Once the ROC verifies it, the NGO will receive a special CSR Registration Number which allows them to carry out CSR projects in India."
    },
    {
        "question": "How CSR-1 application is processed?",
        "answer": "The STP method is used to process the CSR-1 form for NGO registration. There is no need for any human involvement throughout the entire process."
    },
    {
        "question": "What’s the fees for CSR-1 registration?",
        "answer": "The fee we charge is specified in the upper part of this page. Currently, there is no specified government fee for the CSR-1 Filing."
    },
    {
        "question": "What happens once CSR registered?",
        "answer": "Upon successful completion of processing a CSR-1 form, the user will receive an email acknowledgement at the entity's email address. Additionally, the FO User will receive a digitally signed approval letter, along with the CSR Registration number in the format CSRXXXXXXXX, where X is a unique sequential number generated by the system. This information will also be sent to the email address provided in the eform."
    }
]



  
const Home = () => {
    return (
        <div className='services-pages qatar-reg'>
            <Head>
                <title>CSR Registration  | RegisterKaro</title>
                <meta name="description" content="The Ministry of Corporate Affairs, Government of India made the Companies Act, 2013 into law which was a major initiative in making CSR mandatory for companies by requiring them to engage in social welfare projects" />
                <link rel="canonical" href="https://www.registerkaro.in/csr-registration" />
                <link rel="icon" href="/favicon.ico" />
                <meta property="og:title" content="CSR Registration  | RegisterKaro" />
                <meta property="og:description" content="The Ministry of Corporate Affairs, Government of India made the Companies Act, 2013 into law which was a major initiative in making CSR mandatory for companies by requiring them to engage in social welfare projects" />
            </Head>
            <Hero />
            <h1 className='main-heading'>Know About CSR Registration</h1>
            <div className='heading-line'></div>
            <Process />
            <h2 className='main-heading'>Documents Required</h2>
            <div className='heading-line'></div>
            <DocumentRequired />
            <h2 className='main-heading'>Procedure to File CSR</h2>
            <div className='heading-line'></div>
            <ProcedureCsr/>
            <h2 className='main-heading'>Facts About CSR</h2>
            <div className='heading-line'></div>
            <FactsCsr/>
            <h2 className='main-heading'>How RegisterKaro helps you in the Registration process?</h2>
            <div className='heading-line'></div>
            <WhyChoose/>
            <h2 className="main-heading">Why RegisterKaro?</h2>
            <div className='heading-line'></div>
            <WhyRegisterkaro />
            <h2 className="main-heading">FAQs</h2>
            <div className='heading-line'></div>
            <FaqTemplatePVT faqItems={faq} />
        </div>
    )
}
export default Home