import React from 'react'
import certificate from '../../../assets/images/section-8-reg/COI.webp';
import Image from 'next/image';

export const Process = () => {
    return (
        <div className='process flex w-80 m-auto mobile-flex-column-reverse'>
            <div className='flex-5'>
                <p className='text-justify'>In India, a Section 8 Company functions as an NGO dedicated to advancing various fields such as art, science, education, sports, and charitable activities. Unlike Trusts or Societies, profits generated by Section 8 Companies are reinvested to support their stated objectives rather than being distributed to company members. The registration process for a Section 8 Company falls under the jurisdiction of the Ministry of Corporate Affairs (MCA), distinguishing it from Trusts and Societies, which are governed by State Government Registrars. <br />Opting for Section 8 Company registration through RegisterKaro offers distinct advantages over Trusts and Societies. The Section 8 structure enhances credibility with government departments, stakeholders, and potential donors. At RegisterKaro, our proficient team ensures a seamless registration process for your Section 8 Company. With expertise in documentation, application filing, and efficient incorporation, we alleviate your concerns, making the entire process smooth and effective.</p>
                <div className='page-point'>
                    <ul>
                        <ul>
                            <a href="#What" className="scrollTo">
                                <li>What is a Private Limited Company?</li>
                            </a>
                            <a href="#Different" className="scrollTo">
                                <li>Different types of Business Structures in India</li>
                            </a>
                            <a href="#Benefits" className="scrollTo">
                                <li>Benefits of Private Limited Company Registration in India</li>
                            </a>
                            <a href="#Checklist" className="scrollTo">
                                <li>Checklist for Private Limited Company Registration in India</li>
                            </a>
                            <a href="#Documents" className="scrollTo">
                                <li>Documents Required for Company Registration in India</li>
                            </a>
                            <a href="#How" className="scrollTo">
                                <li>How to register a private limited company?</li>
                            </a>
                            <a href="#Time" className="scrollTo">
                                <li>Time Required for Registering a Company Online in India</li>
                            </a>
                            <a href="#HowTo" className="scrollTo">
                                <li>How to Register Your Private Limited Company in India with RegisterKaro?</li>
                            </a>
                            <a href="#WhatDocuments" className="scrollTo">
                                <li>What Documents will you get after Online Company Registration in India?</li>
                            </a>
                            <a href="#Why" className="scrollTo">
                                <li>Why RegisterKaro?</li>
                            </a>
                            <a href="#Faq" className="scrollTo">
                                <li>Frequently Asked Questions</li>
                            </a>
                        </ul>
                    </ul>
                </div>
            </div>
            <div className='flex-5'>
                <p className="small-heading text-center">Section 8 Company Sample Documents</p>
                <div>
                    <Image alt="Private Limited Company sample" className="certificate h-100 w-100" loading="lazy" src={certificate}/>
                </div>
            </div>
        </div>
    )
}
